name: Code Check

on:
    push:
        branches:
            - master

jobs:
    code_check_js:
        name: Code Check JS
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm i -g pnpm && pnpm install

            - name: ESLint check
              run: |
                  npm run lint || exit 1

            - name: Type check
              run: |
                  npm run typecheck || exit 1

            - name: Test
              run: |
                  npm run test || exit 1
